name: chess-env 
channels:
  - conda-forge
dependencies:
  - python==3.10
  - numpy
  - pip
  - pip:
    - chess==1.10.0
    - numpy
    - jupyter
    - aiostream
    - git+https://github.com/eyalk11/sunfish
